apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-arc
  name: hello-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-arc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-arc
    spec:
      containers:
      - image: iorkamrat/hello-arc:latest
        name: hello-arc
        ports:
        - containerPort: 80
        resources: {}
status: {}
