apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-arc
  namespace: hello-arc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-arc
  template:
    metadata:
      labels:
        app: hello-arc
    spec:
      containers:
      - name: hello-arc
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
